### PR TITLE
Rephrasing FLOSS mentioning

### PR DESCRIPTION
**Pull request by porres**
Making a realistic and more productive mentioning of FLOSS Manuals when referring to 'Books about Pd'.

### CODE REVIEW

**Comment by Lucarda** [comment]
@porres 

There are some conflicts with the way we are using Git via web edit.

Check https://github.com/Lucarda/pure-data/pull/6/files (its undoing #5)

may be throw this PR and re-doit now that I had already merged #5

?

**Comment by porres** [comment]
maybe you can manually fix and include my suggestions?

**Comment by Lucarda** [comment]
Yes. I'll do.

Tomorrow may be.
(I think that the trouble was caused by me merging as you were editing)

**Comment by porres** [comment]
well, I redid it, please merge ;)

**Comment by porres** [comment]
>well, I redid it, please merge ;) 

=> https://github.com/Lucarda/pure-data/pull/7

**Pull request closed without merging**
